[package]
name = "outbreak-origins-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

jsonwebtoken = "7.2.0"


serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
bcrypt = "0.10"
actix-cors = "0.5.4"
actix-identity = "0.3.1"
chrono = "0.4"
futures = "0.3.19"
virus_simulator = { path = "virus-simulator"}
<<<<<<< HEAD
<<<<<<< HEAD

diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
r2d2-diesel = "*"
=======
db = {path = "db"}
>>>>>>> f3f18c4 (feat(Server): Connects Server with DB)
=======

diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
r2d2 = "*"
r2d2-diesel = "*"
>>>>>>> 6956b04 (fix(simulator): refactors code and integrates the new changes)

actix = "0.10"
actix-codec = "0.3"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
