[package]
name = "outbreak-origins-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="3"
jsonwebtoken = "7.2.0"
diesel = {version="1.4.4", features=["postgres", "r2d2"]}
r2d2 = "0.8.9"
dotenv = "0.15.0"
serde = {version = "1.0", features=["derive"]}
serde_json = "1.0"
bcrypt = "0.10"
oauth2 = "4.1.0"
actix-cors = "0.5.4"
thiserror = "1.0.30"
time = "0.3.4"
