version: "3"
services:
    serv:
        build: .
        container_name: server_outbreak
        entrypoint: /app/entrypoint.sh
        depends_on:
            - db
        ports:
            - "${PORT}:8081"
        restart: on-failure
        volumes:
          - ./logs:/app/logs

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    db:
        image: postgres:latest
        container_name: db_outbreak
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

volumes:
    pgdata:
